<?php

/*
 * Editor server script for DB table images
 * Automatically generated by http://editor.datatables.net/generator
 */

// DataTables PHP library
include( "lib/DataTables.php" );

// Alias Editor classes so they are easy to use
use
	DataTables\Editor,
	DataTables\Editor\Field,
	DataTables\Editor\Format,
	DataTables\Editor\Join,
	DataTables\Editor\Validate;


// Build our Editor instance and process the data coming from _POST
Editor::inst( $db, 'log_server' )
	->fields(
		Field::inst( 'log_image' ),
		Field::inst( 'log_count' ),
		Field::inst( 'log_type' ),
		Field::inst( 'log_room' ),
		Field::inst( 'log_user' ),
		Field::inst( 'log_date' )

	)
	->process( $_POST )
	->json();

