<?php

/*
 * Editor server script for DB table room
 * Automatically generated by http://editor.datatables.net/generator
 */

// DataTables PHP library
include( "lib/DataTables.php" );

// Alias Editor classes so they are easy to use
use
	DataTables\Editor,
	DataTables\Editor\Field,
	DataTables\Editor\Format,
	DataTables\Editor\Join,
	DataTables\Editor\Validate;


// Build our Editor instance and process the data coming from _POST
Editor::inst( $db, 'room' )
	->fields(
		Field::inst( 'room_name' )
			->validator( 'Validate::required' ),
		Field::inst( 'count_room_pc' )
			->validator( 'Validate::required' ),

		Field::inst( 'add_room_date' )
			->set( false )

			->getFormatter( 'Format::date_sql_to_format', 'd.m.Y' )
			->setFormatter( 'Format::date_format_to_sql', 'd.m.Y' ),
		Field::inst( 'room_admin' ),
		Field::inst( 'iface' )
			->validator( 'Validate::required' )
			)
	->process( $_POST )
	->json();
