<?php

/*
 * Editor server script for DB table login_usernamen
 * Automatically generated by http://editor.datatables.net/generator
 */

// DataTables PHP library
include( "lib/DataTables.php" );

// Alias Editor classes so they are easy to use
use
	DataTables\Editor,
	DataTables\Editor\Field,
	DataTables\Editor\Format,
	DataTables\Editor\Join,
	DataTables\Editor\Validate;


// Build our Editor instance and process the data coming from _POST
Editor::inst( $db, 'login_usernamen' )
	->fields(
		Field::inst( 'first_name' ),
		Field::inst( 'last_name' ),
		Field::inst( 'username' ),
		Field::inst( 'passwort' ),
		Field::inst( 'add_user_date' )
			->set( false )
			->validator( 'Validate::dateFormat', 'd.m.Y' )
			->getFormatter( 'Format::date_sql_to_format', 'd.m.Y' )
			->setFormatter( 'Format::date_format_to_sql', 'd.m.Y' ),
		Field::inst( 'user_access_level' ),
		Field::inst( 'last_user_login' )
			->set( false )
			->validator( 'Validate::dateFormat', 'd.m.Y' )
			->getFormatter( 'Format::date_sql_to_format', 'd.m.Y' )
			->setFormatter( 'Format::date_format_to_sql', 'd.m.Y' )
	)
	->process( $_POST )
	->json();
