<?php

/*
 * Editor server script for DB table room
 * Automatically generated by http://editor.datatables.net/generator
 */

// DataTables PHP library
include( "lib/DataTables.php" );

// Alias Editor classes so they are easy to use
use
	DataTables\Editor,
	DataTables\Editor\Field,
	DataTables\Editor\Format,
	DataTables\Editor\Join,
	DataTables\Editor\Validate;


// Build our Editor instance and process the data coming from _POST
Editor::inst( $db, 'hardware' )
	->fields(
		Field::inst( 'hardware_name' ),
		Field::inst( 'hardware_producer' ),
		Field::inst( 'hardware_ram' ),
		Field::inst( 'hardware_disk' ),
		Field::inst( 'hardware_date' )
			->set( false )
			->validator( 'Validate::dateFormat', 'd.m.Y' )
			->getFormatter( 'Format::date_sql_to_format', 'd.m.Y' )
			->setFormatter( 'Format::date_format_to_sql', 'd.m.Y' ),
		Field::inst( 'hardware_pic' )
				)
	->process( $_POST )
	->json();
