<?php

/*
 * Editor server script for DB table room
 * Automatically generated by http://editor.datatables.net/generator
 */

// DataTables PHP library
include( "lib/DataTables.php" );

// Alias Editor classes so they are easy to use
use
	DataTables\Editor,
	DataTables\Editor\Field,
	DataTables\Editor\Format,
	DataTables\Editor\Join,
	DataTables\Editor\Validate;


// Build our Editor instance and process the data coming from _POST
Editor::inst( $db, 'computer' )
	->fields(
		Field::inst( 'computer_name' ),
		Field::inst( 'computer_mac' ),
		Field::inst( 'computer_ip' ),
		Field::inst( 'computer_room' ),
		Field::inst( 'computer_hardware' ),
		Field::inst( 'computer_visible' )
				)
	->process( $_POST )
	->json();
