<?php

/*
 * Editor server script for DB table room
 * Automatically generated by http://editor.datatables.net/generator
 */

// DataTables PHP library
include( "lib/DataTables.php" );

// Alias Editor classes so they are easy to use
use
	DataTables\Editor,
	DataTables\Editor\Field,
	DataTables\Editor\Format,
	DataTables\Editor\Join,
	DataTables\Editor\Validate;


// Build our Editor instance and process the data coming from _POST
Editor::inst( $db, 'displays' )
	->fields(
		Field::inst( 'display_name' )
			->validator( 'Validate::required' ),
		Field::inst( 'display_room' )
			->validator( 'Validate::required' ),
		Field::inst( 'display_hardware' )
			->validator( 'Validate::required' ),
		Field::inst( 'display_address' )
			->validator( 'Validate::required' )
			)
	->process( $_POST )
	->json();
